/**
 * Regenerate public/sitemap.xml from known routes (keep in sync with src/config/site.ts).
 * Usage: node scripts/generate-sitemap.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const base = (process.env.PUBLIC_SITE_URL || 'https://www.solarhuntington.com').replace(/\/$/, '');
const lastmod = new Date().toISOString().slice(0, 10);

const serviceSlugs = [
  'residential-solar-installation',
  'commercial-solar',
  'battery-storage',
  'solar-repair-maintenance',
  'free-solar-quote',
];
const areaSlugs = [
  'huntington',
  'huntington-station',
  'greenlawn',
  'northport',
  'cold-spring-harbor',
  'centerport',
];

const topLevelPages = [
  '/',
  '/about/',
  '/financing/',
  '/case-studies/',
  '/insights/',
  '/incentives/',
  '/warranty/',
  '/process/',
];

const insightSlugs = [
  'how-much-does-solar-cost-in-huntington-ny-2026',
  'solar-permits-town-of-huntington-2026-walkthrough',
  'tesla-powerwall-vs-enphase-iq-battery-2026',
];

// Cross-product service × area pages generated by tools/page-generator/.
// Add new (service, area) tuples here as pages are generated; the generator
// will also append them automatically in a future phase.
const crossProductPages = [
  ['battery-storage', 'huntington'],
  ['battery-storage', 'northport'],
  ['battery-storage', 'cold-spring-harbor'],
  ['battery-storage', 'huntington-station'],
  ['battery-storage', 'greenlawn'],
  ['battery-storage', 'centerport'],
];

const urls = [
  ...topLevelPages.map((p) => `${base}${p}`),
  ...serviceSlugs.map((s) => `${base}/services/${s}/`),
  ...areaSlugs.map((a) => `${base}/locations/${a}/`),
  ...insightSlugs.map((i) => `${base}/insights/${i}/`),
  ...crossProductPages.map(([s, a]) => `${base}/services/${s}/${a}/`),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((loc) => `  <url><loc>${loc}</loc><lastmod>${lastmod}</lastmod></url>`).join('\n')}
</urlset>
`;

const out = join(__dirname, '../dist/sitemap.xml');
writeFileSync(out, xml, 'utf8');
console.log('Wrote dist/sitemap.xml with', urls.length, 'URLs');
